# Dockerfile that is used for slave Jenkins
FROM jenkins/jenkins:lts
USER root
#install docker client
RUN apt-get update -qq
RUN apt-get install -y apt-utils
RUN apt-get install -qq apt-transport-https ca-certificates curl gnupg2 software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
RUN apt-get update -qq && apt-get install docker-ce -y
RUN usermod -aG docker jenkins
FROM ubuntu
#----------------------------------------------------------------
RUN apt-get update 
RUN apt-get install openjdk-8-jdk -y
WORKDIR /root
RUN mkdir Jenkins
RUN cd Jenkins
RUN pwd > Path  
RUN apt install openssh-server -y
#RUN service ssh status
RUN service ssh start
WORKDIR /root/.ssh
RUN yes | ssh-keygen
RUN mv y id_rsa
RUN mv y.pub id_rsa.pub
RUN cat /id_rsa.pub > authorized_keys
WORKDIR /
# RUN apt-get install git -y
RUN ls -a
RUN service ssh start
