FROM python:3.6-alpine
USER root
COPY ./Booster_CI_CD_Project/ /root/Jenkins/simpleApp
 WORKDIR /usr/src/app
 ENV PYTHONDONTWRITEBYTECODE 1
 ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip 
COPY ./requirements.txt /usr/src/app
RUN pip install -r requirements.txtz
RUN ls /root/Jenkins/simpleApp
RUN python3.6 /root/Jenkins/simpleApp/manage.py makemigrations
RUN python3.6 /root/Jenkins/simpleApp/manage.py migrate
CMD python3.6 /root/Jenkins/simpleApp/manage.py runserver 0.0.0.0:8000
